---
- name: Add group "Office" to remote server
  group:
    name: www-data
    state: present

- name: create user for wordpress
  user:
    name: www-data
    shell: /bin/bash
    group: www-data

#- name: create folder for wordpress
#  file:
#    path: /var/www/chapterOne
#    state: directory
#    recurse: yes

- name: Download and unpack latest WordPress
  vars:
    http_host: "html"
  unarchive:
    src: https://wordpress.org/latest.tar.gz
    dest: "/var/www/{{ http_host }}"
    remote_src: yes
    creates: "/var/www/{{ http_host }}/wordpress"


- name: Set ownership
  vars:
    http_host: "html"
  file:
    path: "/var/www/{{ http_host }}/wordpress"
    state: directory
    recurse: yes
    owner: apache
    group: apache
 

#- name: Set permissions for directories
#  vars:
#    http_host: "chapterOne"
#  shell: "/usr/bin/find /var/www/{{ http_host }}/wordpress/ -type d -exec chmod 750 {} \\;"


- name: Set permissions for wordpress folder
  vars:
    http_host: "html"
  file:
    path: /var/www/{{ http_host }}/wordpress
    state: directory
    mode: '0744'


- name: Set up wp-config
  template:
    src: "files/wp-config.php.j2"
    dest: "/var/www/html/wordpress/wp-config.php"
  notify:
    - restart apache
 
