---
- name: install mariadb
  become: yes
  yum:
    name:
      - mariadb-server
      - MySQL-python
    state: latest
- name: start mariadb
  become: yes
  service:
    name: mariadb
    enabled: true
    state: started
- name: mysql_root_password
  become: yes
  vars:
    mysql_root_password: "Passwords21"
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    user: root
    check_implicit_admin: true
    password: "{{ mysql_root_password }}"
    host: localhost
