---
- name: start mariadb
  service:
    name: mariadb
    enabled: true
    state: started
- name: Create MariaDB database
  mysql_db:
    name: wordpress
    state: present
- name: mysql_root_password
  vars:
    mysql_root_password: "Passwords21"
  mysql_user:
    name: adminuser
    #check_implicit_admin: true
    password: "{{ mysql_root_password }}"
    priv: 'wordpress.*:ALL,GRANT'
    state: present
- name: Removes anonymous user account for localhost
  mysql_user:
    name: ''
    host: localhost
    state: absent
- name: Removes the MySQL test database
  mysql_db: name=test state=absent login_password="" login_user=root