---
- name: install repositories required for wordpress
  become: yes
  import_tasks: prerequisites.yml

- name: install httpd and move http configuration file
  become: yes
  import_tasks: deploy_httpd.yml

- name: enable firewall and enable http/s port
  become: yes
  import_tasks: deploy_firewall.yml
    
- name: install and set up mariadb
  import_tasks: deploy_mariadb.yml

- name: set up wordpress
  become: yes
  import_tasks: deploy_wordpress.yml
