---
# handlers files for apache

- name: restart apache
  become: yes
  service: name=httpd state=restarted
  listen: "restart httpd"
- name: restart mariadb
  become: yes
  service: name=mariadb state=restarted
  listen: "restart mariadb"